### ISSUE TITLE
No *.css files support?!

### ISSUE THREAD

**Issue by Nakilon** [ankushagarwal/nweb#6]

**Comment by coderLMN** [comment]
Just edit nweb23.c source code, add a line

```html
   {"css","text/css"},
```

inside the  `extensions [] = {` definition. 

Adding other file formats is also viable with this method.

**Comment by alexmyczko** [comment]
https://github.com/alexmyczko/nweb updated including your css patch

**Comment by Nakilon** [comment]
IIRC I used busybox docker image that includes httpd.
